# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        items_api_image:
            uri_prefix: /assets/images/uploads/api
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/api'
            namer: App\Service\ApiFixedNamer
            delete_on_update: false
            delete_on_remove: false

        support_image:
            uri_prefix: /assets/images/uploads/support
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/support'
            namer: vich_uploader.namer_smart_unique